# Generated by Django 4.2.2 on 2023-07-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilledForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.TextField()),
                ('Last_name', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Mileage', models.FloatField(default=0)),
                ('Expense_Image', models.ImageField(default='default.jpg', upload_to='Expense_reports')),
                ('Expense_Amount', models.FloatField()),
                ('Client', models.TextField()),
                ('Date', models.DateField()),
                ('Work_type', models.TextField()),
                ('Time_started', models.TimeField()),
                ('Time_ended', models.TimeField()),
                ('Rating', models.IntegerField()),
                ('Notes', models.TextField()),
                ('What_did_you_learn', models.TextField()),
            ],
        ),
    ]
