# Generated by Django 4.2.2 on 2023-07-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caledon_Reno_Work_Hours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', models.IntegerField()),
                ('Resume', models.FileField(default='default.txt', upload_to='Expense_reports')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key', models.TextField()),
                ('Phase', models.TextField()),
                ('Description', models.TextField()),
                ('Specific_Description', models.TextField()),
                ('Unit_cost', models.FloatField()),
                ('Unit_type', models.TextField()),
                ('GC_Rate_10_Mark_Up', models.FloatField()),
                ('Retail_Rate_40_Mark_Up', models.FloatField()),
            ],
        ),
    ]
