# Generated by Django 4.2.2 on 2023-07-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caledon_Reno_Work_Hours', '0002_application_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Phone_Number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='Resume',
            field=models.FileField(default='default.txt', upload_to='Resumes'),
        ),
    ]
