# Generated by Django 4.2.2 on 2023-09-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caledon_Reno_Work_Hours', '0003_alter_application_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', models.IntegerField(default=0)),
                ('Blueprint_and_Images', models.FileField(default='default.txt', upload_to='Estimates')),
            ],
        ),
    ]
