# Generated by Django 4.2.2 on 2023-09-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caledon_Reno_Work_Hours', '0004_estimate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='GC_Rate_10_Mark_Up',
            new_name='GC_Rate_10',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Retail_Rate_40_Mark_Up',
            new_name='Retail_Rate_40',
        ),
        migrations.AlterField(
            model_name='estimate',
            name='Blueprint_and_Images',
            field=models.ImageField(default='default.jpg', upload_to='Estimates'),
        ),
    ]
