# Generated by Django 4.2.2 on 2023-10-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caledon_Reno_Work_Hours', '0006_rename_blueprint_and_images_estimate_blueprints_and_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='Phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filledform',
            name='Expense_Amount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='filledform',
            name='Expense_Image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='Expense_reports'),
        ),
    ]
