# Generated by Django 4.2.2 on 2023-10-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caledon_Reno_Work_Hours', '0007_alter_estimate_phone_alter_filledform_expense_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filledform',
            name='Expense_Amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='filledform',
            name='Notes',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='filledform',
            name='What_did_you_learn',
            field=models.TextField(default='N/A'),
        ),
    ]
